services:
  postgres:
    image: postgres:15-alpine
    container_name: kitchen-butler-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kitchen_butler
      POSTGRES_PASSWORD: kitchen_butler_pass
      POSTGRES_DB: kitchen_butler
    volumes:
      - kitchen_butler_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitchen_butler"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: kitchen-butler-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kitchenbutler.io
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  kitchen_butler_data: